const personal=v=>({reminder:v.reminder||'',reminderTime:v.reminderTime||''});
const details=v=>{if(!v.name?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(v.date||'')||!/^\d{2}:\d{2}$/.test(v.time||''))throw Error('Enter an appointment name, date, and time.');return {name:v.name.trim(),date:v.date,time:v.time,for:v.for||'',place:v.place||'',note:v.note||'',video:!!v.video,changeNotified:v.changeNotified||[]}};
export async function localAppointmentRequest(home,op='list',id='',v={},account,members){
 const key='chillallot.personal-appointments.'+home,actor=account.id;let rows=JSON.parse(localStorage.getItem(key)||'null');
 if(!rows){const legacy=JSON.parse(localStorage.getItem('chillallot.appointments.'+home)||'[]');rows=legacy.map((a,i)=>({id:a.id||'legacy-'+i,creatorId:null,record:details(a),revision:1,preferences:Object.fromEntries(members.map(m=>{const saved=a.memberReminders?.find(r=>r.member===m.name);return [m.id,{...personal(saved?{reminder:saved.reminder,reminderTime:saved.time}:a),removed:false}]}))}));}
 const a=rows.find(a=>a.id===id);
 if(op==='create'){if(a)throw Error('Appointment already exists.');const prefs={[actor]:{...personal(v),removed:false}};for(const r of v.memberReminders||[]){const matches=members.filter(m=>r.userId?m.id===r.userId:m.name===r.member);if(matches.length===1&&matches[0].id!==actor)prefs[matches[0].id]={reminder:r.reminder||'',reminderTime:r.time||'',removed:false};}rows.push({id,creatorId:actor,record:details(v),revision:1,preferences:prefs});}
 else if(op!=='list'){if(!a||a.preferences[actor]?.removed)throw Error('Appointment not found.');if(op==='assign'){if(!members.some(m=>m.id===actor&&m.role==='Owner')||a.creatorId)throw Error('Only a household owner can assign an unassigned appointment.');if(!members.some(m=>m.id===v.creatorId))throw Error('Choose a household member.');a.creatorId=v.creatorId;a.revision++;}else if(op==='settings'){a.preferences[actor]={...personal(v),removed:false};}else if(op==='remove'){a.preferences[actor]={...a.preferences[actor],removed:true,reminder:'',reminderTime:''};}else if(op==='edit'){if(a.creatorId!==actor)throw Error('Only the creator can edit appointment details.');if(v.expectedRevision!==a.revision)throw Error('This appointment changed in another window. Reopen it before saving.');a.record=details(v);a.revision++;a.preferences[actor]={...personal(v),removed:false};}else throw Error('Unknown appointment action.');}
 localStorage.setItem(key,JSON.stringify(rows));return rows.filter(a=>!a.preferences[actor]?.removed).map(a=>({...a.record,id:a.id,creatorId:a.creatorId||null,revision:a.revision,...personal(a.preferences[actor]||{}),notified:[],memberReminders:[]}));
}
