import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {deviceUnlockSupported,registerUnlock,verifyUnlock,shouldLock} from '../lib/appUnlock.js';
const Context=createContext(null);
export const useAppUnlock=()=>useContext(Context);
export function SignOutAction({className='text-button auth-switch'}){const unlock=useAppUnlock();return <button type="button" className={className} onClick={unlock.requestSignOut}>Sign out</button>;}
export default function AppUnlockBoundary({account,available,onSignOut,children}){
 const key='chillallot.app-unlock.'+account.id;
 const [config,setConfig]=useState(()=>{try{const c=JSON.parse(localStorage.getItem(key));return c?.credentialId?{...c,delay:['0','10','30','60'].includes(String(c.delay))?String(c.delay):'30'}:{enabled:false,delay:'30'};}catch{return {enabled:false,delay:'30'}}});
 const [locked,setLocked]=useState(!!config.enabled),[away,setAway]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[supported,setSupported]=useState(null);
 const [confirmSignOut,setConfirmSignOut]=useState(false),[signOutBusy,setSignOutBusy]=useState(false),[signOutError,setSignOutError]=useState(''),[theme,setTheme]=useState(()=>localStorage.getItem('chillallot.unlock-theme.'+account.id)||'Dark Cozy');
 const content=useRef(null);
 useEffect(()=>{const update=()=>{const value=content.current?.querySelector('[data-theme]')?.getAttribute('data-theme');if(value){setTheme(value);localStorage.setItem('chillallot.unlock-theme.'+account.id,value)}};update();const observer=new MutationObserver(update);if(content.current)observer.observe(content.current,{subtree:true,attributes:true,attributeFilter:['data-theme'],childList:true});return()=>observer.disconnect()},[account.id]);
 const hiddenAt=useRef(null),focus=useRef(null),unlockButton=useRef(null);
 const save=c=>{localStorage.setItem(key,JSON.stringify(c));setConfig(c)};
 useEffect(()=>{let active=true;deviceUnlockSupported().then(value=>{if(active)setSupported(value)}).catch(()=>{if(active)setSupported(false)});return()=>{active=false}},[]);
 useEffect(()=>{if(!config.enabled)return;let timer;const hide=()=>{if(hiddenAt.current===null)hiddenAt.current=Date.now();setAway(true);clearTimeout(timer);timer=setTimeout(()=>setLocked(true),Number(config.delay)*1000)};const reveal=()=>{if(shouldLock(hiddenAt.current,Date.now(),config.delay))setLocked(true);hiddenAt.current=null;setAway(false);clearTimeout(timer)};const visibility=()=>document.visibilityState==='hidden'?hide():reveal();document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',hide);window.addEventListener('pageshow',visibility);if(document.visibilityState==='hidden')hide();return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pagehide',hide);window.removeEventListener('pageshow',visibility)}},[config.enabled,config.delay]);
 useEffect(()=>{if(locked){focus.current=document.activeElement;unlockButton.current?.focus()}else focus.current?.focus?.()},[locked]);
 const run=async action=>{if(busy)return;setBusy(true);setError('');try{await action()}catch(e){setError(e.name==='NotAllowedError'?'Device verification was cancelled. Please try again.':e.message)}finally{setBusy(false)}};
 const enable=()=>run(async()=>{if(!available||!supported)throw Error('Device unlock is not available here.');const result=await registerUnlock();if(!result.verified||!result.credentialId)throw Error('Device setup was not verified.');save({...config,enabled:true,credentialId:result.credentialId});setLocked(false)});
 const unlock=()=>run(async()=>{await verifyUnlock(config.credentialId);hiddenAt.current=null;setLocked(false)});
 return <Context.Provider value={{config,supported,available,busy,error,enable,requestSignOut:()=>{setSignOutError('');setConfirmSignOut(true)},disable:()=>save({...config,enabled:false}),setDelay:delay=>save({...config,delay})}}><div className="app unlock-shell" data-theme={theme}><div ref={content} className="unlock-content" inert={locked||away||confirmSignOut?true:undefined} style={locked||away?{visibility:'hidden'}:undefined}>{children}</div>{locked&&<div className="app-unlock-screen" inert={confirmSignOut?true:undefined} role="dialog" aria-modal="true" aria-labelledby="unlock-title"><section className="auth-card"><div className="brand">Chill<span>Allot</span></div><h1 id="unlock-title">Unlock ChillAllot</h1><p>Use your device’s fingerprint, face recognition, or screen lock.</p><button ref={unlockButton} className="primary auth-submit" disabled={busy} onClick={unlock}>{busy?'Verifying…':'Unlock'}</button>{error&&<p role="alert" className="form-message">{error}</p>}<button className="text-button auth-switch" disabled={busy} onClick={()=>setConfirmSignOut(true)}>Sign out</button></section></div>}{confirmSignOut&&<div className="signout-overlay" onKeyDown={e=>{if(e.key==='Escape'&&!signOutBusy)setConfirmSignOut(false);if(e.key==='Tab'){const buttons=[...e.currentTarget.querySelectorAll('button:not(:disabled)')];if(!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><section className="signout-dialog" role="dialog" aria-modal="true" aria-labelledby="signout-title"><h2 id="signout-title">Sign out?</h2><p>You’ll need to sign in again to open your account.</p><div className="modal-actions"><button type="button" autoFocus className="outline" disabled={signOutBusy} onClick={()=>setConfirmSignOut(false)}>Stay signed in</button><button type="button" className="outline" disabled={signOutBusy} onClick={async()=>{setSignOutBusy(true);setSignOutError('');try{await onSignOut();setConfirmSignOut(false)}catch(e){setSignOutError(e.message)}finally{setSignOutBusy(false)}}}>{signOutBusy?'Signing out…':'Sign out'}</button></div>{signOutError&&<p role="alert" className="form-message">{signOutError}</p>}</section></div>}</div></Context.Provider>;
}
