import React, { useEffect, useRef, useState } from 'react';
import EmojiChooser from './EmojiChooser.jsx';

const colors={sage:'#b8c5a4',blue:'#91b5e8',peach:'#e0b69b',lavender:'#c5b4e8',coral:'#e59b88',gold:'#e4c477'};
const avatars={initial:'',leaf:'🌿',sun:'☀️',moon:'🌙',cat:'🐈',dog:'🐕',home:'🏠'};
export const badgeColor=value=>/^#[0-9a-f]{6}$/i.test(value||'')?value:colors[value]||colors.sage;
export const avatarText=value=>value?.startsWith('initial:')?value.slice(8):value?.startsWith('emoji:')?value.slice(6):avatars[value]||'';
export const isPhoto=value=>/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(value||'')&&value.length<=80000;
export function MemberBadge({member,small=false,current=false}){
 const photo=isPhoto(member.avatarKey);
 return <span className={'avatar avatar-custom'+(small?' avatar-small':'')+(current?' avatar-current':'')} style={{'--badge-color':badgeColor(member.badgeColor)}}>{photo?<img src={member.avatarKey} alt=""/>:<span className="badge-symbol">{avatarText(member.avatarKey)||member.name?.[0]||'?'}</span>}</span>;
}
function hueColor(h){const a=(n)=>(n+h/30)%12;const f=n=>Math.round(255*(.64-.24*Math.max(-1,Math.min(a(n)-3,9-a(n),1)))).toString(16).padStart(2,'0');return '#'+f(0)+f(8)+f(4)}
function colorHue(value){const c=badgeColor(value),[r,g,b]=[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;if(!d)return 0;return Math.round(((max===r?(g-b)/d:max===g?(b-r)/d+2:(r-g)/d+4)*60+360)%360)}
export function validEmoji(value){return [...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(value.trim())].length===1&&/\p{Extended_Pictographic}|\p{Regional_Indicator}|[0-9#*]\uFE0F?\u20E3/u.test(value)}
export default function BadgeEditor({name,saved,onSave,preview=false}){
 const [draft,setDraft]=useState(saved),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[photo,setPhoto]=useState(null),[zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[hue,setHue]=useState(90);
 const canvas=useRef(null),loadId=useRef(0),saving=useRef(false);
 useEffect(()=>{setDraft(saved);setHue(colorHue(saved.color))},[saved.color,saved.avatar]);
 useEffect(()=>()=>{loadId.current++},[]);
 useEffect(()=>{if(!photo)return;const c=canvas.current,ctx=c.getContext('2d'),size=Math.min(photo.naturalWidth,photo.naturalHeight)/zoom,sx=(photo.naturalWidth-size)*x/100,sy=(photo.naturalHeight-size)*y/100;ctx.fillStyle='#fff';ctx.fillRect(0,0,192,192);ctx.drawImage(photo,sx,sy,size,size,0,0,192,192)},[photo,zoom,x,y]);
 const change=patch=>{setDraft(d=>({...d,...patch}));if(patch.color)setHue(colorHue(patch.color));setNotice('');setError('')};
 const upload=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');setNotice('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('Choose a JPG, PNG, or WebP photo smaller than 10 MB.');return}const id=++loadId.current;try{const url=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read this photo.'));r.readAsDataURL(file)});const img=new Image();img.src=url;await img.decode();if(id!==loadId.current)return;setZoom(1);setX(50);setY(50);setPhoto(img)}catch{if(id===loadId.current)setError('Could not open this photo. Try a JPG or PNG.')}};
 const save=async()=>{if(saving.current)return;const value=draft.avatar;if(value.startsWith('initial:')&&!/^[A-Z]$/.test(value.slice(8))){setError('Enter one letter from A to Z.');return}if(value.startsWith('emoji:')&&!validEmoji(value.slice(6))){setError('Choose or paste one emoji.');return}saving.current=true;setBusy(true);setError('');setNotice('');try{await onSave(draft);setNotice(preview?'Saved on this device for preview.':'Saved. Your household will see your updated badge.')}catch(err){setError(err.message||'Could not save. Your changes are still here; try again.')}finally{saving.current=false;setBusy(false)}};
 const dirty=draft.color!==saved.color||draft.avatar!==saved.avatar;
 return <section className="badge-settings"><div className="badge-settings-heading"><MemberBadge member={{name,badgeColor:draft.color,avatarKey:draft.avatar}} current/><div><strong>Your badge appearance</strong><small>The ring marks your own badge. Choose your look, then save.</small></div></div><fieldset disabled={busy}><label className="badge-slider-label">Badge color<input type="range" min="0" max="359" value={hue} aria-label="Badge color" onChange={e=>{setHue(+e.target.value);change({color:hueColor(+e.target.value)})}} className="badge-hue"/></label><label className="initial-choice">Your initial<input aria-label="Your initial" data-preserve-input autoComplete="off" maxLength="1" value={draft.avatar.startsWith('initial:')?draft.avatar.slice(8):draft.avatar==='initial'?name?.[0]?.toUpperCase()||'':''} placeholder="G" onChange={e=>change({avatar:'initial:'+e.target.value.toUpperCase()})}/><small>Choose any letter, even if your household name is different.</small></label><EmojiChooser value={draft.avatar.startsWith('emoji:')?draft.avatar.slice(6):draft.avatar.startsWith('initial:')?'':avatarText(draft.avatar)} onChange={emoji=>change({avatar:emoji?'emoji:'+emoji:'initial'})}/><label className="photo-upload">Use a photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/><small>JPG, PNG, or WebP, up to 10 MB. Only the cropped image is saved.</small></label>{photo&&<div className="photo-crop"><strong>Crop your photo</strong><canvas ref={canvas} width="192" height="192" aria-label="Photo crop preview"/><label>Zoom<input aria-label="Photo zoom" type="range" min="1" max="4" step=".05" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label>Horizontal position<input type="range" min="0" max="100" value={x} onChange={e=>setX(+e.target.value)}/></label><label>Vertical position<input type="range" min="0" max="100" value={y} onChange={e=>setY(+e.target.value)}/></label><div className="badge-save-row"><button type="button" className="outline" onClick={()=>{const value=canvas.current.toDataURL('image/jpeg',.82);if(!isPhoto(value)){setError('Photo is too large. Please try another photo.');return}change({avatar:value});setPhoto(null)}}>Use cropped photo</button><button type="button" className="plain" onClick={()=>setPhoto(null)}>Cancel crop</button></div></div>}</fieldset><div className="badge-save-row"><button type="button" className="primary" disabled={busy||!dirty||!!photo} onClick={save}>{busy?'Saving…':'Save changes'}</button><button type="button" className="plain" disabled={busy||(!dirty&&!photo)} onClick={()=>{loadId.current++;setDraft(saved);setPhoto(null);setError('');setNotice('')}}>Discard changes</button></div>{error&&<p role="alert" className="form-message">{error}</p>}{notice&&<p role="status" className="badge-notice">{notice}</p>}</section>
}
