import React,{useState,useEffect,useRef} from 'react';
export default function HouseholdVisibility({household,hiddenHouseholds=[],onChange,compact=false}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[restore,setRestore]=useState(false);
 const dialog=useRef(null),trigger=useRef(null);
 useEffect(()=>{if(confirm){dialog.current?.showModal()}else if(dialog.current?.open){dialog.current.close();trigger.current?.focus()}},[confirm]);
 if(!onChange)return null;
 const change=async(id,hidden)=>{setBusy(true);setError('');try{await onChange(id,hidden)}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(compact)return <div className="household-discreet"><div className="household-link-row">{household&&<button type="button" className="text-button" ref={trigger} disabled={busy} onClick={()=>{setConfirm(true);setRestore(false)}}>Hide household</button>}{hiddenHouseholds.length>0&&<button type="button" className="text-button" onClick={()=>{setRestore(!restore);setConfirm(false)}}>Hidden households</button>}</div>{confirm&&<dialog ref={dialog} className="household-hide-dialog" aria-labelledby="hide-household-title" onCancel={e=>{if(busy)e.preventDefault();else setConfirm(false)}}><h2 id="hide-household-title">Hide household?</h2><p className="modal-description"> You’re still a member, and your assigned chores, bills, and reminders remain active.</p><div className="modal-actions"><button type="button" className="outline" autoFocus disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button><button type="button" className="outline" disabled={busy} onClick={()=>change(household.id,true)}>Hide household</button></div>{error&&<p role="alert" className="form-message">{error}</p>}</dialog>}{restore&&hiddenHouseholds.map(h=><div className="hidden-household-row" key={h.id}><span>{h.name}</span><button type="button" className="text-button" disabled={busy} onClick={()=>change(h.id,false)}>Restore</button></div>)}{error&&<p role="alert" className="form-message">{error}</p>}</div>;
 return <section className="household-visibility">{household&&<><button type="button" className="outline" disabled={busy} onClick={()=>change(household.id,true)}>Hide household</button><p className="modal-description">Hides this household from your view. You’re still a member, and your assigned chores, bills, and reminders remain active.</p></>}{hiddenHouseholds.length>0&&<><h2>Hidden households</h2>{hiddenHouseholds.map(h=><div className="hidden-household-row" key={h.id}><span>{h.name}</span><button type="button" className="outline" disabled={busy} onClick={()=>change(h.id,false)}>Restore</button></div>)}</>}{error&&<p className="form-message" role="alert">{error}</p>}</section>
}
