import React,{useState} from 'react';
import {leaveHousehold} from '../lib/householdBackend.js';

export default function LeaveHousehold({household,account,onLeft}) {
 const others=(household.members||[]).filter(m=>m.id!==account.id);
 const [open,setOpen]=useState(false),[successor,setSuccessor]=useState(''),[summary,setSummary]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const close=()=>{if(!busy){setOpen(false);setSummary(null);setError('')}};
 const start=()=>{setSuccessor(others.find(m=>m.role==='Owner')?.id||others[0]?.id||'');setSummary(null);setError('');setOpen(true)};
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{if(!summary)setSummary(await leaveHousehold(household.id,successor,false));else{await leaveHousehold(household.id,successor,true);await onLeft();setOpen(false)}}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <><div className="leave-household"><button type="button" className="outline" onClick={start}>Leave household</button></div>{open&&<div className="overlay" onClick={close}><form className="modal leave-household-modal" role="dialog" aria-modal="true" aria-label="Leave household" onClick={e=>e.stopPropagation()} onSubmit={submit}><div className="eyebrow">LEAVE HOUSEHOLD</div><h2>{summary?'Are you sure?':household.name}</h2>{!others.length?<p>You’re the only member. Invite someone and transfer ownership before leaving.</p>:summary?<><p className="modal-description">You will leave {household.name}. {summary.successorName} will take over the shared entries you created.{summary.transfersOwnership&&' They will also become the household owner.'}</p><p className="modal-description">Shared items and payment history stay with the household. You will be removed from chore rotations.</p>{summary.privateBills>0&&<p className="modal-description">Your {summary.privateBills} private bill{summary.privateBills===1?'':'s'} will move to a personal household only you can access.</p>}{summary.unpaidShares>0&&<p className="form-message">{summary.unpaidShares} unpaid bill share{summary.unpaidShares===1?' needs':'s need'} review by the household. No payment amounts will be changed.</p>}</>:<><p className="modal-description">Choose who will take over the shared entries you created.{household.role==='owner'&&' Leaving will also transfer household ownership to this person.'}</p><label>Take over shared entries<select value={successor} onChange={e=>setSuccessor(e.target.value)} required>{others.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></>}{error&&<p role="alert" className="form-message">{error}</p>}<div className="modal-actions"><button type="button" className="outline" disabled={busy} onClick={close}>Cancel</button>{!!others.length&&<button type="submit" className="primary" disabled={busy}>{busy?'Please wait…':summary?'Leave household':'Continue'}</button>}</div></form></div>}</>;
}
