import React, { useState } from 'react';
import { requestPasswordReset, changePassword } from '../lib/householdBackend.js';

export function ForgotPassword({onBack,expired=false}) {
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 return <main className="auth-shell"><div className="auth-card"><h1>{expired?"Reset password":"Forgot password?"}</h1><p>{expired?"This reset link is expired or incomplete. Enter your email to request a new link.":"Enter your account email to request a reset link."}</p><form autoComplete="off" onSubmit={async e=>{e.preventDefault();if(busy)return;const email=new FormData(e.currentTarget).get('email');setBusy(true);setError('');setMessage('');try{await requestPasswordReset(email);setMessage('If an account uses that email, a reset link will arrive shortly. Check your spam folder too.')}catch(err){setError(err.message)}finally{setBusy(false)}}}><label>Email<input name="email" type="email" autoComplete="off" required/></label><button className="primary auth-submit" disabled={busy}>{busy?'Sending…':'Send reset link'}</button></form>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="form-message">{error}</p>}<button className="text-button auth-switch" disabled={busy} onClick={onBack}>Back to sign in</button></div></main>;
}

export function PasswordForm({recovery=false,onSaved,preview=false}) {
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 return <section className="password-settings"><h2>{recovery?'Set a new password':'Change password'}</h2><p>{recovery?'Choose your new password to finish resetting your account.':'Update the password for your account on all devices.'}</p>{preview?<p>Sign in to your real account to change its password.</p>:<form autoComplete="off" onSubmit={async e=>{e.preventDefault();if(busy)return;const form=e.currentTarget,v=Object.fromEntries(new FormData(form));setError('');setMessage('');if(v.password!==v.confirm){setError('The new passwords do not match.');return}setBusy(true);try{await changePassword(v.password,recovery?undefined:v.current);form.reset();setMessage('Your password has been updated.');onSaved?.()}catch(err){setError(err.message||'Could not update your password. Try again.')}finally{setBusy(false)}}}>{!recovery&&<label>Current password<input name="current" type="password" autoComplete="off" required/></label>}<label>New password<input name="password" type="password" autoComplete="off" minLength="8" required/></label><label>Confirm new password<input name="confirm" type="password" autoComplete="off" minLength="8" required/></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save password'}</button></form>}{error&&<p role="alert" className="form-message">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
